In [1]:
import tensorflow as tf
from tensorflow.contrib import learn
import data_helpers
import numpy as np

tf.flags.DEFINE_float('dev_sample_percetage',0.1,'Percetafe of training data to use for vaildation')
FLAGS = tf.flags.FLAGS
FLAGS.flag_values_dict()

{'dev_sample_percetage': 0.1}

In [2]:
file_path = r'F:\post graduate\raw_data\bugs.csv'
x_text,y = data_helpers.load_data_and_labels(file_path)
max_document_length = max(len(x.split(' ')) for x in x_text)
vocab_processor = learn.preprocessing.VocabularyProcessor(max_document_length,min_frequency=2)
x = np.array(list(vocab_processor.fit_transform(x_text)))


Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.


In [3]:
print(max_document_length)

38


In [26]:
x

array([[  1,   2,  34, ...,   0,   0,   0],
       [  1,   2,  34, ...,   0,   0,   0],
       [  1,   2,  34, ...,   0,   0,   0],
       ...,
       [  1,  13,  14, ...,   0,   0,   0],
       [ 26,  25, 151, ...,   0,   0,   0],
       [  1,   2, 426, ...,   0,   0,   0]], dtype=int64)

In [4]:
shuffle_indices = np.random.permutation(np.arange(len(y)))

In [5]:
x_shuffled = x[shuffle_indices]

In [6]:
x_shuffled

array([[  1,  13,  14, ...,   0,   0,   0],
       [  1,   2,  16, ...,   0,   0,   0],
       [  1,   4,   3, ...,   0,   0,   0],
       ...,
       [128, 128, 404, ...,   0,   0,   0],
       [  1,   2,  19, ...,   0,   0,   0],
       [  1,   4,  27, ...,   0,   0,   0]], dtype=int64)

In [7]:
dev_sample_index = -1 * int(FLAGS.dev_sample_percentage * float(len(y)))

UnrecognizedFlagError: Unknown command line flag 'f'

In [36]:
dev_sample_index

-12525

In [34]:
print(len(y))

62625


In [5]:
filter_sizes= list(map(int, '3,4,5'.split(',')))

In [6]:
filter_sizes

[3, 4, 5]

In [8]:
one_hot = np.zeros((10, 10), int)

In [9]:
one_hot

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
np.fill_diagonal(one_hot, 1)

In [11]:
one_hot

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [2]:
a = [i for i in range(100)]

In [ ]:
import tensorflow as tf
import pickle
import numpy as np

vocab = []
embd = []
emb_size = 200
filename = r'F:\word2vec\glove.6B\glove.6B.200d.txt'
vocab.append('unk')  # 装载不认识的词
embd.append([0] * emb_size)  # 这个emb_size可能需要指定
file = open(filename, 'r', encoding='utf-8')
for line in file.readlines():
    row = line.strip().split(' ')
    vocab.append(row[0])
    embd.append(row[1:])
print('Loaded GloVe!')
file.close()
with open(r'F:\bug_triage\emb_and_dict\dict200.pickle', 'wb') as f:
    pickle.dump(vocab, f)
with open(r'F:\bug_triage\emb_and_dict\embedding200.pickle', 'wb') as f:
    pickle.dump(embd, f)


In [56]:
from nltk.corpus import stopwords
import nltk
import pandas as pd
import numpy as np
import re
stop_word = stopwords.words("english")
def load_data_and_labels(data_file):
    df = pd.read_csv(data_file, encoding='latin-1')
    text = df['x_input']
    label = df['y_label']
    x_text = [clean_str(sent) for sent in text]
    
    set_label = set(label)
    length = len(set_label)
    dic_label = dict(zip(range(len(set_label)), set_label))
    y = list()
    for name in label:
        l = [0] * length
        for k, v in dic_label.items():
            if name is v:
                l[k] = 1
                y.append(l)
    return [x_text, np.asarray(y)]
def clean_str(string):
    porter=nltk.PorterStemmer()
    string = re.sub(r"\(.*?\)", " ", string)
    string = re.sub(r'[^a-zA-Z \']', " ", string)
    string = [porter.stem(w) for w in string.split() if w not in stop_word ]
    string = " ".join(string)
    return string.lower()

In [12]:
print(stop_word)
x,y = load_data_and_labels(r'F:\post graduate\dataset\filted_data.csv')
clean_str("Tools CDT cdt-core Main thread hangs due to deadlock whilst indexing")
porter=nltk.PorterStemmer()

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [2]:
import tensorflow as tf
from tensorflow.contrib import learn

In [4]:
vocab_processor = learn.preprocessing.VocabularyProcessor(100, min_frequency=2)

Instructions for updating:
Please use tensorflow/transform or tf.data.
Instructions for updating:
Please use tensorflow/transform or tf.data.


In [2]:
import pickle
import numpy as np
with open(r'F:\bug_triage\emb_and_dict\embedding100.pickle', 'rb') as f:
        emb = pickle.load(f)
        emb = np.asarray(emb)
        emb = emb.astype(np.float32)

In [7]:
emb.shape

(400001, 100)

In [8]:
with open(r'F:\bug_triage\emb_and_dict\dict100.pickle', 'rb') as f:
    vocab = pickle.load(f)

In [6]:
print(" Evaluation:\n\
2019-05-22 15:09:10.030217: step 12400, loss 1.85833, acc 0.553313\n\
2019-05-22T15:09:10.127956: step 12401, loss 1.13926, acc 0.78125\n\
2019-05-22T15:09:10.242649: step 12402, loss 1.21519, acc 0.671875\n\
2019-05-22T15:09:10.350361: step 12403, loss 1.41069, acc 0.609375\n\
2019-05-22T15:09:10.459071: step 12404, loss 1.15076, acc 0.6875\n\
2019-05-22T15:09:10.576756: step 12405, loss 1.26219, acc 0.59375\n\
2019-05-22T15:09:10.683470: step 12406, loss 1.13599, acc 0.6875\n\
2019-05-22T15:09:10.793176: step 12407, loss 0.838597, acc 0.828125\n\
2019-05-22T15:09:10.899891: step 12408, loss 1.26273, acc 0.65625\n\
2019-05-22T15:09:11.012589: step 12409, loss 0.907215, acc 0.8125\n\
2019-05-22T15:09:11.127282: step 12410, loss 1.21336, acc 0.671875\n\
2019-05-22T15:09:11.241976: step 12411, loss 1.19814, acc 0.65625\n\
2019-05-22T15:09:11.355672: step 12412, loss 1.42266, acc 0.65625\n\
2019-05-22T15:09:11.467373: step 12413, loss 1.17634, acc 0.65625\n\
2019-05-22T15:09:11.579074: step 12414, loss 1.3206, acc 0.71875\n\
2019-05-22T15:09:11.690776: step 12415, loss 1.23893, acc 0.671875\n\
2019-05-22T15:09:11.799484: step 12416, loss 1.32823, acc 0.609375\n\
2019-05-22T15:09:11.910188: step 12417, loss 1.05198, acc 0.71875\n\
2019-05-22T15:09:12.020892: step 12418, loss 1.34072, acc 0.625\n\
2019-05-22T15:09:12.132593: step 12419, loss 1.1722, acc 0.671875")



 Evaluation:
2019-05-22 15:09:10.030217: step 12400, loss 1.85833, acc 0.553313
2019-05-22T15:09:10.127956: step 12401, loss 1.13926, acc 0.78125
2019-05-22T15:09:10.242649: step 12402, loss 1.21519, acc 0.671875
2019-05-22T15:09:10.350361: step 12403, loss 1.41069, acc 0.609375
2019-05-22T15:09:10.459071: step 12404, loss 1.15076, acc 0.6875
2019-05-22T15:09:10.576756: step 12405, loss 1.26219, acc 0.59375
2019-05-22T15:09:10.683470: step 12406, loss 1.13599, acc 0.6875
2019-05-22T15:09:10.793176: step 12407, loss 0.838597, acc 0.828125
2019-05-22T15:09:10.899891: step 12408, loss 1.26273, acc 0.65625
2019-05-22T15:09:11.012589: step 12409, loss 0.907215, acc 0.8125
2019-05-22T15:09:11.127282: step 12410, loss 1.21336, acc 0.671875
2019-05-22T15:09:11.241976: step 12411, loss 1.19814, acc 0.65625
2019-05-22T15:09:11.355672: step 12412, loss 1.42266, acc 0.65625
2019-05-22T15:09:11.467373: step 12413, loss 1.17634, acc 0.65625
2019-05-22T15:09:11.579074: step 12414, loss 1.3206, acc 0.